/* eslint-disable @typescript-eslint/restrict-plus-operands */
import { type NextPage } from "next";
import Head from "next/head";
import UserPosts from "~/components/user-posts";
import Products from "~/components/products";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center">
        <h1 className="text-4xl">Main Page</h1>
        <div className="flex flex-col gap-5">
          {/* <UserPosts /> */}
          <Products />
        </div>
      </div>
    </>
  );
};

export default Home;
